import { createFileRoute } from "@tanstack/react-router";
import { ShoppingCart, Receipt, TrendingUp, CornerUpLeft, Wallet, RefreshCcw } from "lucide-react";
import { PageHeader } from "@/components/affiliate/PageHeader";
import { KpiCard, KpiGrid } from "@/components/affiliate/KpiCard";
import { WallShell } from "@/components/affiliate/WallShell";
import { FilterBar } from "@/components/affiliate/FilterBar";
import { DataTableShell } from "@/components/affiliate/DataTableShell";
import { Tabs } from "@/components/affiliate/StatusBadge";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/affiliate-manager/sales")({
  head: () => ({ meta: [{ title: "Sales — Affiliate Manager" }] }),
  component: SalesWall,
});

function SalesWall() {
  return (
    <>
      <PageHeader
        title="Sales"
        description="Sales generated by affiliates with revenue, refunds and returns."
        crumbs={[{ label: "Affiliate Manager" }, { label: "Sales" }]}
        actions={<><Button variant="outline" size="sm">Reconcile</Button><Button size="sm">Record Sale</Button></>}
      />
      <Tabs items={["All Sales", "Today", "Last 7d", "Last 30d", "Refunds", "Returns", "Reconciliation"]} />
      <WallShell>
        <KpiGrid>
          <KpiCard label="Sales 30d" value="0" icon={<ShoppingCart className="size-4" />} tone="primary" />
          <KpiCard label="Revenue 30d" value="—" icon={<TrendingUp className="size-4" />} tone="success" />
          <KpiCard label="Invoices" value="0" icon={<Receipt className="size-4" />} />
          <KpiCard label="Refunds" value="0" icon={<RefreshCcw className="size-4" />} tone="warning" />
          <KpiCard label="Returns" value="0" icon={<CornerUpLeft className="size-4" />} />
          <KpiCard label="Net Revenue" value="—" icon={<Wallet className="size-4" />} />
        </KpiGrid>
        <FilterBar placeholder="Search sales by order, customer, affiliate…" filters={["Status", "Affiliate", "Product", "Country", "Date"]} />
        <DataTableShell
          columns={[
            { key: "sale", label: "Sale" },
            { key: "customer", label: "Customer" },
            { key: "affiliate", label: "Affiliate" },
            { key: "product", label: "Product" },
            { key: "amount", label: "Amount", align: "right" },
            { key: "commission", label: "Commission", align: "right" },
            { key: "date", label: "Date" },
            { key: "status", label: "Status" },
          ]}
          emptyIcon={ShoppingCart}
          emptyTitle="No sales yet"
          emptyDescription="Sales attributed to affiliates appear here with commission breakdown."
        />
      </WallShell>
    </>
  );
}
