/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AffiliateManagerRouteImport } from './routes/affiliate-manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateManagerIndexRouteImport } from './routes/affiliate-manager.index'

const AffiliateManagerRoute = AffiliateManagerRouteImport.update({
  id: '/affiliate-manager',
  path: '/affiliate-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateManagerIndexRoute = AffiliateManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliateManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRouteWithChildren
  '/affiliate-manager/': typeof AffiliateManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRouteWithChildren
  '/affiliate-manager/': typeof AffiliateManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/affiliate-manager' | '/affiliate-manager/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/affiliate-manager'
  id: '__root__' | '/' | '/affiliate-manager' | '/affiliate-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateManagerRoute: typeof AffiliateManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/affiliate-manager': {
      id: '/affiliate-manager'
      path: '/affiliate-manager'
      fullPath: '/affiliate-manager'
      preLoaderRoute: typeof AffiliateManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-manager/': {
      id: '/affiliate-manager/'
      path: '/'
      fullPath: '/affiliate-manager/'
      preLoaderRoute: typeof AffiliateManagerIndexRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
  }
}

interface AffiliateManagerRouteChildren {
  AffiliateManagerIndexRoute: typeof AffiliateManagerIndexRoute
}

const AffiliateManagerRouteChildren: AffiliateManagerRouteChildren = {
  AffiliateManagerIndexRoute: AffiliateManagerIndexRoute,
}

const AffiliateManagerRouteWithChildren =
  AffiliateManagerRoute._addFileChildren(AffiliateManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateManagerRoute: AffiliateManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
