/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AffiliateManagerRouteImport } from './routes/affiliate-manager'
import { Route as IndexRouteImport } from './routes/index'

const AffiliateManagerRoute = AffiliateManagerRouteImport.update({
  id: '/affiliate-manager',
  path: '/affiliate-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/affiliate-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/affiliate-manager'
  id: '__root__' | '/' | '/affiliate-manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateManagerRoute: typeof AffiliateManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/affiliate-manager': {
      id: '/affiliate-manager'
      path: '/affiliate-manager'
      fullPath: '/affiliate-manager'
      preLoaderRoute: typeof AffiliateManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateManagerRoute: AffiliateManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
