/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateManagerRouteImport } from './routes/affiliate-manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateManagerIndexRouteImport } from './routes/affiliate-manager.index'
import { Route as AffiliateManagerWalletRouteImport } from './routes/affiliate-manager.wallet'
import { Route as AffiliateManagerSupportRouteImport } from './routes/affiliate-manager.support'
import { Route as AffiliateManagerSettingsRouteImport } from './routes/affiliate-manager.settings'
import { Route as AffiliateManagerSearchRouteImport } from './routes/affiliate-manager.search'
import { Route as AffiliateManagerSalesRouteImport } from './routes/affiliate-manager.sales'
import { Route as AffiliateManagerReportsRouteImport } from './routes/affiliate-manager.reports'
import { Route as AffiliateManagerReferralNetworkRouteImport } from './routes/affiliate-manager.referral-network'
import { Route as AffiliateManagerReferralCodesRouteImport } from './routes/affiliate-manager.referral-codes'
import { Route as AffiliateManagerRealtimeTestRouteImport } from './routes/affiliate-manager.realtime-test'
import { Route as AffiliateManagerProductsRouteImport } from './routes/affiliate-manager.products'
import { Route as AffiliateManagerPerformanceRouteImport } from './routes/affiliate-manager.performance'
import { Route as AffiliateManagerPayoutsRouteImport } from './routes/affiliate-manager.payouts'
import { Route as AffiliateManagerOrdersRouteImport } from './routes/affiliate-manager.orders'
import { Route as AffiliateManagerMarketplaceRouteImport } from './routes/affiliate-manager.marketplace'
import { Route as AffiliateManagerMarketingRouteImport } from './routes/affiliate-manager.marketing'
import { Route as AffiliateManagerLeadsRouteImport } from './routes/affiliate-manager.leads'
import { Route as AffiliateManagerImportRouteImport } from './routes/affiliate-manager.import'
import { Route as AffiliateManagerExportRouteImport } from './routes/affiliate-manager.export'
import { Route as AffiliateManagerDocumentsRouteImport } from './routes/affiliate-manager.documents'
import { Route as AffiliateManagerCustomersRouteImport } from './routes/affiliate-manager.customers'
import { Route as AffiliateManagerCouponsRouteImport } from './routes/affiliate-manager.coupons'
import { Route as AffiliateManagerComplianceRouteImport } from './routes/affiliate-manager.compliance'
import { Route as AffiliateManagerCommunicationRouteImport } from './routes/affiliate-manager.communication'
import { Route as AffiliateManagerCommissionsRouteImport } from './routes/affiliate-manager.commissions'
import { Route as AffiliateManagerCampaignsRouteImport } from './routes/affiliate-manager.campaigns'
import { Route as AffiliateManagerBulkActionsRouteImport } from './routes/affiliate-manager.bulk-actions'
import { Route as AffiliateManagerApplicationsRouteImport } from './routes/affiliate-manager.applications'
import { Route as AffiliateManagerAnalyticsRouteImport } from './routes/affiliate-manager.analytics'
import { Route as AffiliateManagerAffiliatesRouteImport } from './routes/affiliate-manager.affiliates'
import { Route as AffiliateManagerAffiliateLinksRouteImport } from './routes/affiliate-manager.affiliate-links'
import { Route as AffiliateManagerAffiliatesIdRouteImport } from './routes/affiliate-manager.affiliates.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateManagerRoute = AffiliateManagerRouteImport.update({
  id: '/affiliate-manager',
  path: '/affiliate-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateManagerIndexRoute = AffiliateManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerWalletRoute = AffiliateManagerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerSupportRoute = AffiliateManagerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerSettingsRoute =
  AffiliateManagerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerSearchRoute = AffiliateManagerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerSalesRoute = AffiliateManagerSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerReportsRoute = AffiliateManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerReferralNetworkRoute =
  AffiliateManagerReferralNetworkRouteImport.update({
    id: '/referral-network',
    path: '/referral-network',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerReferralCodesRoute =
  AffiliateManagerReferralCodesRouteImport.update({
    id: '/referral-codes',
    path: '/referral-codes',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerRealtimeTestRoute =
  AffiliateManagerRealtimeTestRouteImport.update({
    id: '/realtime-test',
    path: '/realtime-test',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerProductsRoute =
  AffiliateManagerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerPerformanceRoute =
  AffiliateManagerPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerPayoutsRoute = AffiliateManagerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerOrdersRoute = AffiliateManagerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerMarketplaceRoute =
  AffiliateManagerMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerMarketingRoute =
  AffiliateManagerMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerLeadsRoute = AffiliateManagerLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerImportRoute = AffiliateManagerImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerExportRoute = AffiliateManagerExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerDocumentsRoute =
  AffiliateManagerDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerCustomersRoute =
  AffiliateManagerCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerCouponsRoute = AffiliateManagerCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AffiliateManagerRoute,
} as any)
const AffiliateManagerComplianceRoute =
  AffiliateManagerComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerCommunicationRoute =
  AffiliateManagerCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerCommissionsRoute =
  AffiliateManagerCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerCampaignsRoute =
  AffiliateManagerCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerBulkActionsRoute =
  AffiliateManagerBulkActionsRouteImport.update({
    id: '/bulk-actions',
    path: '/bulk-actions',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerApplicationsRoute =
  AffiliateManagerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerAnalyticsRoute =
  AffiliateManagerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerAffiliatesRoute =
  AffiliateManagerAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerAffiliateLinksRoute =
  AffiliateManagerAffiliateLinksRouteImport.update({
    id: '/affiliate-links',
    path: '/affiliate-links',
    getParentRoute: () => AffiliateManagerRoute,
  } as any)
const AffiliateManagerAffiliatesIdRoute =
  AffiliateManagerAffiliatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AffiliateManagerAffiliatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRouteWithChildren
  '/auth': typeof AuthRoute
  '/affiliate-manager/affiliate-links': typeof AffiliateManagerAffiliateLinksRoute
  '/affiliate-manager/affiliates': typeof AffiliateManagerAffiliatesRouteWithChildren
  '/affiliate-manager/analytics': typeof AffiliateManagerAnalyticsRoute
  '/affiliate-manager/applications': typeof AffiliateManagerApplicationsRoute
  '/affiliate-manager/bulk-actions': typeof AffiliateManagerBulkActionsRoute
  '/affiliate-manager/campaigns': typeof AffiliateManagerCampaignsRoute
  '/affiliate-manager/commissions': typeof AffiliateManagerCommissionsRoute
  '/affiliate-manager/communication': typeof AffiliateManagerCommunicationRoute
  '/affiliate-manager/compliance': typeof AffiliateManagerComplianceRoute
  '/affiliate-manager/coupons': typeof AffiliateManagerCouponsRoute
  '/affiliate-manager/customers': typeof AffiliateManagerCustomersRoute
  '/affiliate-manager/documents': typeof AffiliateManagerDocumentsRoute
  '/affiliate-manager/export': typeof AffiliateManagerExportRoute
  '/affiliate-manager/import': typeof AffiliateManagerImportRoute
  '/affiliate-manager/leads': typeof AffiliateManagerLeadsRoute
  '/affiliate-manager/marketing': typeof AffiliateManagerMarketingRoute
  '/affiliate-manager/marketplace': typeof AffiliateManagerMarketplaceRoute
  '/affiliate-manager/orders': typeof AffiliateManagerOrdersRoute
  '/affiliate-manager/payouts': typeof AffiliateManagerPayoutsRoute
  '/affiliate-manager/performance': typeof AffiliateManagerPerformanceRoute
  '/affiliate-manager/products': typeof AffiliateManagerProductsRoute
  '/affiliate-manager/realtime-test': typeof AffiliateManagerRealtimeTestRoute
  '/affiliate-manager/referral-codes': typeof AffiliateManagerReferralCodesRoute
  '/affiliate-manager/referral-network': typeof AffiliateManagerReferralNetworkRoute
  '/affiliate-manager/reports': typeof AffiliateManagerReportsRoute
  '/affiliate-manager/sales': typeof AffiliateManagerSalesRoute
  '/affiliate-manager/search': typeof AffiliateManagerSearchRoute
  '/affiliate-manager/settings': typeof AffiliateManagerSettingsRoute
  '/affiliate-manager/support': typeof AffiliateManagerSupportRoute
  '/affiliate-manager/wallet': typeof AffiliateManagerWalletRoute
  '/affiliate-manager/': typeof AffiliateManagerIndexRoute
  '/affiliate-manager/affiliates/$id': typeof AffiliateManagerAffiliatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/affiliate-manager/affiliate-links': typeof AffiliateManagerAffiliateLinksRoute
  '/affiliate-manager/affiliates': typeof AffiliateManagerAffiliatesRouteWithChildren
  '/affiliate-manager/analytics': typeof AffiliateManagerAnalyticsRoute
  '/affiliate-manager/applications': typeof AffiliateManagerApplicationsRoute
  '/affiliate-manager/bulk-actions': typeof AffiliateManagerBulkActionsRoute
  '/affiliate-manager/campaigns': typeof AffiliateManagerCampaignsRoute
  '/affiliate-manager/commissions': typeof AffiliateManagerCommissionsRoute
  '/affiliate-manager/communication': typeof AffiliateManagerCommunicationRoute
  '/affiliate-manager/compliance': typeof AffiliateManagerComplianceRoute
  '/affiliate-manager/coupons': typeof AffiliateManagerCouponsRoute
  '/affiliate-manager/customers': typeof AffiliateManagerCustomersRoute
  '/affiliate-manager/documents': typeof AffiliateManagerDocumentsRoute
  '/affiliate-manager/export': typeof AffiliateManagerExportRoute
  '/affiliate-manager/import': typeof AffiliateManagerImportRoute
  '/affiliate-manager/leads': typeof AffiliateManagerLeadsRoute
  '/affiliate-manager/marketing': typeof AffiliateManagerMarketingRoute
  '/affiliate-manager/marketplace': typeof AffiliateManagerMarketplaceRoute
  '/affiliate-manager/orders': typeof AffiliateManagerOrdersRoute
  '/affiliate-manager/payouts': typeof AffiliateManagerPayoutsRoute
  '/affiliate-manager/performance': typeof AffiliateManagerPerformanceRoute
  '/affiliate-manager/products': typeof AffiliateManagerProductsRoute
  '/affiliate-manager/realtime-test': typeof AffiliateManagerRealtimeTestRoute
  '/affiliate-manager/referral-codes': typeof AffiliateManagerReferralCodesRoute
  '/affiliate-manager/referral-network': typeof AffiliateManagerReferralNetworkRoute
  '/affiliate-manager/reports': typeof AffiliateManagerReportsRoute
  '/affiliate-manager/sales': typeof AffiliateManagerSalesRoute
  '/affiliate-manager/search': typeof AffiliateManagerSearchRoute
  '/affiliate-manager/settings': typeof AffiliateManagerSettingsRoute
  '/affiliate-manager/support': typeof AffiliateManagerSupportRoute
  '/affiliate-manager/wallet': typeof AffiliateManagerWalletRoute
  '/affiliate-manager': typeof AffiliateManagerIndexRoute
  '/affiliate-manager/affiliates/$id': typeof AffiliateManagerAffiliatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate-manager': typeof AffiliateManagerRouteWithChildren
  '/auth': typeof AuthRoute
  '/affiliate-manager/affiliate-links': typeof AffiliateManagerAffiliateLinksRoute
  '/affiliate-manager/affiliates': typeof AffiliateManagerAffiliatesRouteWithChildren
  '/affiliate-manager/analytics': typeof AffiliateManagerAnalyticsRoute
  '/affiliate-manager/applications': typeof AffiliateManagerApplicationsRoute
  '/affiliate-manager/bulk-actions': typeof AffiliateManagerBulkActionsRoute
  '/affiliate-manager/campaigns': typeof AffiliateManagerCampaignsRoute
  '/affiliate-manager/commissions': typeof AffiliateManagerCommissionsRoute
  '/affiliate-manager/communication': typeof AffiliateManagerCommunicationRoute
  '/affiliate-manager/compliance': typeof AffiliateManagerComplianceRoute
  '/affiliate-manager/coupons': typeof AffiliateManagerCouponsRoute
  '/affiliate-manager/customers': typeof AffiliateManagerCustomersRoute
  '/affiliate-manager/documents': typeof AffiliateManagerDocumentsRoute
  '/affiliate-manager/export': typeof AffiliateManagerExportRoute
  '/affiliate-manager/import': typeof AffiliateManagerImportRoute
  '/affiliate-manager/leads': typeof AffiliateManagerLeadsRoute
  '/affiliate-manager/marketing': typeof AffiliateManagerMarketingRoute
  '/affiliate-manager/marketplace': typeof AffiliateManagerMarketplaceRoute
  '/affiliate-manager/orders': typeof AffiliateManagerOrdersRoute
  '/affiliate-manager/payouts': typeof AffiliateManagerPayoutsRoute
  '/affiliate-manager/performance': typeof AffiliateManagerPerformanceRoute
  '/affiliate-manager/products': typeof AffiliateManagerProductsRoute
  '/affiliate-manager/realtime-test': typeof AffiliateManagerRealtimeTestRoute
  '/affiliate-manager/referral-codes': typeof AffiliateManagerReferralCodesRoute
  '/affiliate-manager/referral-network': typeof AffiliateManagerReferralNetworkRoute
  '/affiliate-manager/reports': typeof AffiliateManagerReportsRoute
  '/affiliate-manager/sales': typeof AffiliateManagerSalesRoute
  '/affiliate-manager/search': typeof AffiliateManagerSearchRoute
  '/affiliate-manager/settings': typeof AffiliateManagerSettingsRoute
  '/affiliate-manager/support': typeof AffiliateManagerSupportRoute
  '/affiliate-manager/wallet': typeof AffiliateManagerWalletRoute
  '/affiliate-manager/': typeof AffiliateManagerIndexRoute
  '/affiliate-manager/affiliates/$id': typeof AffiliateManagerAffiliatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate-manager'
    | '/auth'
    | '/affiliate-manager/affiliate-links'
    | '/affiliate-manager/affiliates'
    | '/affiliate-manager/analytics'
    | '/affiliate-manager/applications'
    | '/affiliate-manager/bulk-actions'
    | '/affiliate-manager/campaigns'
    | '/affiliate-manager/commissions'
    | '/affiliate-manager/communication'
    | '/affiliate-manager/compliance'
    | '/affiliate-manager/coupons'
    | '/affiliate-manager/customers'
    | '/affiliate-manager/documents'
    | '/affiliate-manager/export'
    | '/affiliate-manager/import'
    | '/affiliate-manager/leads'
    | '/affiliate-manager/marketing'
    | '/affiliate-manager/marketplace'
    | '/affiliate-manager/orders'
    | '/affiliate-manager/payouts'
    | '/affiliate-manager/performance'
    | '/affiliate-manager/products'
    | '/affiliate-manager/realtime-test'
    | '/affiliate-manager/referral-codes'
    | '/affiliate-manager/referral-network'
    | '/affiliate-manager/reports'
    | '/affiliate-manager/sales'
    | '/affiliate-manager/search'
    | '/affiliate-manager/settings'
    | '/affiliate-manager/support'
    | '/affiliate-manager/wallet'
    | '/affiliate-manager/'
    | '/affiliate-manager/affiliates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/affiliate-manager/affiliate-links'
    | '/affiliate-manager/affiliates'
    | '/affiliate-manager/analytics'
    | '/affiliate-manager/applications'
    | '/affiliate-manager/bulk-actions'
    | '/affiliate-manager/campaigns'
    | '/affiliate-manager/commissions'
    | '/affiliate-manager/communication'
    | '/affiliate-manager/compliance'
    | '/affiliate-manager/coupons'
    | '/affiliate-manager/customers'
    | '/affiliate-manager/documents'
    | '/affiliate-manager/export'
    | '/affiliate-manager/import'
    | '/affiliate-manager/leads'
    | '/affiliate-manager/marketing'
    | '/affiliate-manager/marketplace'
    | '/affiliate-manager/orders'
    | '/affiliate-manager/payouts'
    | '/affiliate-manager/performance'
    | '/affiliate-manager/products'
    | '/affiliate-manager/realtime-test'
    | '/affiliate-manager/referral-codes'
    | '/affiliate-manager/referral-network'
    | '/affiliate-manager/reports'
    | '/affiliate-manager/sales'
    | '/affiliate-manager/search'
    | '/affiliate-manager/settings'
    | '/affiliate-manager/support'
    | '/affiliate-manager/wallet'
    | '/affiliate-manager'
    | '/affiliate-manager/affiliates/$id'
  id:
    | '__root__'
    | '/'
    | '/affiliate-manager'
    | '/auth'
    | '/affiliate-manager/affiliate-links'
    | '/affiliate-manager/affiliates'
    | '/affiliate-manager/analytics'
    | '/affiliate-manager/applications'
    | '/affiliate-manager/bulk-actions'
    | '/affiliate-manager/campaigns'
    | '/affiliate-manager/commissions'
    | '/affiliate-manager/communication'
    | '/affiliate-manager/compliance'
    | '/affiliate-manager/coupons'
    | '/affiliate-manager/customers'
    | '/affiliate-manager/documents'
    | '/affiliate-manager/export'
    | '/affiliate-manager/import'
    | '/affiliate-manager/leads'
    | '/affiliate-manager/marketing'
    | '/affiliate-manager/marketplace'
    | '/affiliate-manager/orders'
    | '/affiliate-manager/payouts'
    | '/affiliate-manager/performance'
    | '/affiliate-manager/products'
    | '/affiliate-manager/realtime-test'
    | '/affiliate-manager/referral-codes'
    | '/affiliate-manager/referral-network'
    | '/affiliate-manager/reports'
    | '/affiliate-manager/sales'
    | '/affiliate-manager/search'
    | '/affiliate-manager/settings'
    | '/affiliate-manager/support'
    | '/affiliate-manager/wallet'
    | '/affiliate-manager/'
    | '/affiliate-manager/affiliates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateManagerRoute: typeof AffiliateManagerRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-manager': {
      id: '/affiliate-manager'
      path: '/affiliate-manager'
      fullPath: '/affiliate-manager'
      preLoaderRoute: typeof AffiliateManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-manager/': {
      id: '/affiliate-manager/'
      path: '/'
      fullPath: '/affiliate-manager/'
      preLoaderRoute: typeof AffiliateManagerIndexRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/wallet': {
      id: '/affiliate-manager/wallet'
      path: '/wallet'
      fullPath: '/affiliate-manager/wallet'
      preLoaderRoute: typeof AffiliateManagerWalletRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/support': {
      id: '/affiliate-manager/support'
      path: '/support'
      fullPath: '/affiliate-manager/support'
      preLoaderRoute: typeof AffiliateManagerSupportRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/settings': {
      id: '/affiliate-manager/settings'
      path: '/settings'
      fullPath: '/affiliate-manager/settings'
      preLoaderRoute: typeof AffiliateManagerSettingsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/search': {
      id: '/affiliate-manager/search'
      path: '/search'
      fullPath: '/affiliate-manager/search'
      preLoaderRoute: typeof AffiliateManagerSearchRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/sales': {
      id: '/affiliate-manager/sales'
      path: '/sales'
      fullPath: '/affiliate-manager/sales'
      preLoaderRoute: typeof AffiliateManagerSalesRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/reports': {
      id: '/affiliate-manager/reports'
      path: '/reports'
      fullPath: '/affiliate-manager/reports'
      preLoaderRoute: typeof AffiliateManagerReportsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/referral-network': {
      id: '/affiliate-manager/referral-network'
      path: '/referral-network'
      fullPath: '/affiliate-manager/referral-network'
      preLoaderRoute: typeof AffiliateManagerReferralNetworkRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/referral-codes': {
      id: '/affiliate-manager/referral-codes'
      path: '/referral-codes'
      fullPath: '/affiliate-manager/referral-codes'
      preLoaderRoute: typeof AffiliateManagerReferralCodesRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/realtime-test': {
      id: '/affiliate-manager/realtime-test'
      path: '/realtime-test'
      fullPath: '/affiliate-manager/realtime-test'
      preLoaderRoute: typeof AffiliateManagerRealtimeTestRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/products': {
      id: '/affiliate-manager/products'
      path: '/products'
      fullPath: '/affiliate-manager/products'
      preLoaderRoute: typeof AffiliateManagerProductsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/performance': {
      id: '/affiliate-manager/performance'
      path: '/performance'
      fullPath: '/affiliate-manager/performance'
      preLoaderRoute: typeof AffiliateManagerPerformanceRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/payouts': {
      id: '/affiliate-manager/payouts'
      path: '/payouts'
      fullPath: '/affiliate-manager/payouts'
      preLoaderRoute: typeof AffiliateManagerPayoutsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/orders': {
      id: '/affiliate-manager/orders'
      path: '/orders'
      fullPath: '/affiliate-manager/orders'
      preLoaderRoute: typeof AffiliateManagerOrdersRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/marketplace': {
      id: '/affiliate-manager/marketplace'
      path: '/marketplace'
      fullPath: '/affiliate-manager/marketplace'
      preLoaderRoute: typeof AffiliateManagerMarketplaceRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/marketing': {
      id: '/affiliate-manager/marketing'
      path: '/marketing'
      fullPath: '/affiliate-manager/marketing'
      preLoaderRoute: typeof AffiliateManagerMarketingRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/leads': {
      id: '/affiliate-manager/leads'
      path: '/leads'
      fullPath: '/affiliate-manager/leads'
      preLoaderRoute: typeof AffiliateManagerLeadsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/import': {
      id: '/affiliate-manager/import'
      path: '/import'
      fullPath: '/affiliate-manager/import'
      preLoaderRoute: typeof AffiliateManagerImportRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/export': {
      id: '/affiliate-manager/export'
      path: '/export'
      fullPath: '/affiliate-manager/export'
      preLoaderRoute: typeof AffiliateManagerExportRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/documents': {
      id: '/affiliate-manager/documents'
      path: '/documents'
      fullPath: '/affiliate-manager/documents'
      preLoaderRoute: typeof AffiliateManagerDocumentsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/customers': {
      id: '/affiliate-manager/customers'
      path: '/customers'
      fullPath: '/affiliate-manager/customers'
      preLoaderRoute: typeof AffiliateManagerCustomersRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/coupons': {
      id: '/affiliate-manager/coupons'
      path: '/coupons'
      fullPath: '/affiliate-manager/coupons'
      preLoaderRoute: typeof AffiliateManagerCouponsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/compliance': {
      id: '/affiliate-manager/compliance'
      path: '/compliance'
      fullPath: '/affiliate-manager/compliance'
      preLoaderRoute: typeof AffiliateManagerComplianceRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/communication': {
      id: '/affiliate-manager/communication'
      path: '/communication'
      fullPath: '/affiliate-manager/communication'
      preLoaderRoute: typeof AffiliateManagerCommunicationRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/commissions': {
      id: '/affiliate-manager/commissions'
      path: '/commissions'
      fullPath: '/affiliate-manager/commissions'
      preLoaderRoute: typeof AffiliateManagerCommissionsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/campaigns': {
      id: '/affiliate-manager/campaigns'
      path: '/campaigns'
      fullPath: '/affiliate-manager/campaigns'
      preLoaderRoute: typeof AffiliateManagerCampaignsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/bulk-actions': {
      id: '/affiliate-manager/bulk-actions'
      path: '/bulk-actions'
      fullPath: '/affiliate-manager/bulk-actions'
      preLoaderRoute: typeof AffiliateManagerBulkActionsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/applications': {
      id: '/affiliate-manager/applications'
      path: '/applications'
      fullPath: '/affiliate-manager/applications'
      preLoaderRoute: typeof AffiliateManagerApplicationsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/analytics': {
      id: '/affiliate-manager/analytics'
      path: '/analytics'
      fullPath: '/affiliate-manager/analytics'
      preLoaderRoute: typeof AffiliateManagerAnalyticsRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/affiliates': {
      id: '/affiliate-manager/affiliates'
      path: '/affiliates'
      fullPath: '/affiliate-manager/affiliates'
      preLoaderRoute: typeof AffiliateManagerAffiliatesRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/affiliate-links': {
      id: '/affiliate-manager/affiliate-links'
      path: '/affiliate-links'
      fullPath: '/affiliate-manager/affiliate-links'
      preLoaderRoute: typeof AffiliateManagerAffiliateLinksRouteImport
      parentRoute: typeof AffiliateManagerRoute
    }
    '/affiliate-manager/affiliates/$id': {
      id: '/affiliate-manager/affiliates/$id'
      path: '/$id'
      fullPath: '/affiliate-manager/affiliates/$id'
      preLoaderRoute: typeof AffiliateManagerAffiliatesIdRouteImport
      parentRoute: typeof AffiliateManagerAffiliatesRoute
    }
  }
}

interface AffiliateManagerAffiliatesRouteChildren {
  AffiliateManagerAffiliatesIdRoute: typeof AffiliateManagerAffiliatesIdRoute
}

const AffiliateManagerAffiliatesRouteChildren: AffiliateManagerAffiliatesRouteChildren =
  {
    AffiliateManagerAffiliatesIdRoute: AffiliateManagerAffiliatesIdRoute,
  }

const AffiliateManagerAffiliatesRouteWithChildren =
  AffiliateManagerAffiliatesRoute._addFileChildren(
    AffiliateManagerAffiliatesRouteChildren,
  )

interface AffiliateManagerRouteChildren {
  AffiliateManagerAffiliateLinksRoute: typeof AffiliateManagerAffiliateLinksRoute
  AffiliateManagerAffiliatesRoute: typeof AffiliateManagerAffiliatesRouteWithChildren
  AffiliateManagerAnalyticsRoute: typeof AffiliateManagerAnalyticsRoute
  AffiliateManagerApplicationsRoute: typeof AffiliateManagerApplicationsRoute
  AffiliateManagerBulkActionsRoute: typeof AffiliateManagerBulkActionsRoute
  AffiliateManagerCampaignsRoute: typeof AffiliateManagerCampaignsRoute
  AffiliateManagerCommissionsRoute: typeof AffiliateManagerCommissionsRoute
  AffiliateManagerCommunicationRoute: typeof AffiliateManagerCommunicationRoute
  AffiliateManagerComplianceRoute: typeof AffiliateManagerComplianceRoute
  AffiliateManagerCouponsRoute: typeof AffiliateManagerCouponsRoute
  AffiliateManagerCustomersRoute: typeof AffiliateManagerCustomersRoute
  AffiliateManagerDocumentsRoute: typeof AffiliateManagerDocumentsRoute
  AffiliateManagerExportRoute: typeof AffiliateManagerExportRoute
  AffiliateManagerImportRoute: typeof AffiliateManagerImportRoute
  AffiliateManagerLeadsRoute: typeof AffiliateManagerLeadsRoute
  AffiliateManagerMarketingRoute: typeof AffiliateManagerMarketingRoute
  AffiliateManagerMarketplaceRoute: typeof AffiliateManagerMarketplaceRoute
  AffiliateManagerOrdersRoute: typeof AffiliateManagerOrdersRoute
  AffiliateManagerPayoutsRoute: typeof AffiliateManagerPayoutsRoute
  AffiliateManagerPerformanceRoute: typeof AffiliateManagerPerformanceRoute
  AffiliateManagerProductsRoute: typeof AffiliateManagerProductsRoute
  AffiliateManagerRealtimeTestRoute: typeof AffiliateManagerRealtimeTestRoute
  AffiliateManagerReferralCodesRoute: typeof AffiliateManagerReferralCodesRoute
  AffiliateManagerReferralNetworkRoute: typeof AffiliateManagerReferralNetworkRoute
  AffiliateManagerReportsRoute: typeof AffiliateManagerReportsRoute
  AffiliateManagerSalesRoute: typeof AffiliateManagerSalesRoute
  AffiliateManagerSearchRoute: typeof AffiliateManagerSearchRoute
  AffiliateManagerSettingsRoute: typeof AffiliateManagerSettingsRoute
  AffiliateManagerSupportRoute: typeof AffiliateManagerSupportRoute
  AffiliateManagerWalletRoute: typeof AffiliateManagerWalletRoute
  AffiliateManagerIndexRoute: typeof AffiliateManagerIndexRoute
}

const AffiliateManagerRouteChildren: AffiliateManagerRouteChildren = {
  AffiliateManagerAffiliateLinksRoute: AffiliateManagerAffiliateLinksRoute,
  AffiliateManagerAffiliatesRoute: AffiliateManagerAffiliatesRouteWithChildren,
  AffiliateManagerAnalyticsRoute: AffiliateManagerAnalyticsRoute,
  AffiliateManagerApplicationsRoute: AffiliateManagerApplicationsRoute,
  AffiliateManagerBulkActionsRoute: AffiliateManagerBulkActionsRoute,
  AffiliateManagerCampaignsRoute: AffiliateManagerCampaignsRoute,
  AffiliateManagerCommissionsRoute: AffiliateManagerCommissionsRoute,
  AffiliateManagerCommunicationRoute: AffiliateManagerCommunicationRoute,
  AffiliateManagerComplianceRoute: AffiliateManagerComplianceRoute,
  AffiliateManagerCouponsRoute: AffiliateManagerCouponsRoute,
  AffiliateManagerCustomersRoute: AffiliateManagerCustomersRoute,
  AffiliateManagerDocumentsRoute: AffiliateManagerDocumentsRoute,
  AffiliateManagerExportRoute: AffiliateManagerExportRoute,
  AffiliateManagerImportRoute: AffiliateManagerImportRoute,
  AffiliateManagerLeadsRoute: AffiliateManagerLeadsRoute,
  AffiliateManagerMarketingRoute: AffiliateManagerMarketingRoute,
  AffiliateManagerMarketplaceRoute: AffiliateManagerMarketplaceRoute,
  AffiliateManagerOrdersRoute: AffiliateManagerOrdersRoute,
  AffiliateManagerPayoutsRoute: AffiliateManagerPayoutsRoute,
  AffiliateManagerPerformanceRoute: AffiliateManagerPerformanceRoute,
  AffiliateManagerProductsRoute: AffiliateManagerProductsRoute,
  AffiliateManagerRealtimeTestRoute: AffiliateManagerRealtimeTestRoute,
  AffiliateManagerReferralCodesRoute: AffiliateManagerReferralCodesRoute,
  AffiliateManagerReferralNetworkRoute: AffiliateManagerReferralNetworkRoute,
  AffiliateManagerReportsRoute: AffiliateManagerReportsRoute,
  AffiliateManagerSalesRoute: AffiliateManagerSalesRoute,
  AffiliateManagerSearchRoute: AffiliateManagerSearchRoute,
  AffiliateManagerSettingsRoute: AffiliateManagerSettingsRoute,
  AffiliateManagerSupportRoute: AffiliateManagerSupportRoute,
  AffiliateManagerWalletRoute: AffiliateManagerWalletRoute,
  AffiliateManagerIndexRoute: AffiliateManagerIndexRoute,
}

const AffiliateManagerRouteWithChildren =
  AffiliateManagerRoute._addFileChildren(AffiliateManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateManagerRoute: AffiliateManagerRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
